import { useState } from "react";
import { BarChart3, Check, Package, Pencil, Settings2, ShoppingBag } from "lucide-react";
import { Link } from "wouter";
import { Footer, SiteNav } from "@/components/storefront";
import { useI18n } from "@/lib/i18n";
import { products, formatPrice } from "@shared/catalog";
import { trpc } from "@/lib/trpc";

const fulfillmentOptions = ["pending", "processing", "shipped", "completed"] as const;
const statusKa: Record<string, string> = { pending: "მოლოდინში", processing: "მუშავდება", shipped: "გაგზავნილია", completed: "დასრულებულია" };

export default function AdminPage() {
  const { language, t, productTitle } = useI18n();
  const [tab, setTab] = useState<"overview" | "orders" | "products" | "settings">("overview");
  const overview = trpc.admin.overview.useQuery();
  const orderQuery = trpc.admin.orders.useQuery();
  const updateFulfillment = trpc.admin.updateFulfillment.useMutation({ onSuccess: () => orderQuery.refetch() });
  const updateProduct = trpc.admin.updateProduct.useMutation();
  const stats = overview.data;
  const titles = { overview: language === "ka" ? "დილა მშვიდობისა." : "Good morning.", orders: language === "ka" ? "შეკვეთები." : "Orders.", products: language === "ka" ? "პროდუქტები." : "Products.", settings: language === "ka" ? "პარამეტრები." : "Settings." };
  return <div className="site-shell"><SiteNav /><div className="admin-shell"><aside className="admin-sidebar"><div className="eyebrow">{language === "ka" ? "ადმინისტრირება" : "Back office"}</div><h2>scratchme<br /><span style={{ color: "var(--coral)" }}>control.</span></h2><nav className="admin-nav"><button className={tab === "overview" ? "active" : ""} onClick={() => setTab("overview")}><BarChart3 size={15} style={{ verticalAlign: "-3px", marginRight: 8 }} /> {language === "ka" ? "მიმოხილვა" : "Overview"}</button><button className={tab === "orders" ? "active" : ""} onClick={() => setTab("orders")}><ShoppingBag size={15} style={{ verticalAlign: "-3px", marginRight: 8 }} /> {t("nav.cart")}</button><button className={tab === "products" ? "active" : ""} onClick={() => setTab("products")}><Package size={15} style={{ verticalAlign: "-3px", marginRight: 8 }} /> {language === "ka" ? "პროდუქტები" : "Products"}</button><button className={tab === "settings" ? "active" : ""} onClick={() => setTab("settings")}><Settings2 size={15} style={{ verticalAlign: "-3px", marginRight: 8 }} /> {language === "ka" ? "პარამეტრები" : "Settings"}</button></nav><Link href="/" className="nav-link" style={{ display: "block", marginTop: 40, fontSize: 12 }}>← {language === "ka" ? "მაღაზიის ნახვა" : "View storefront"}</Link></aside><main className="admin-main"><div className="eyebrow">{language === "ka" ? "ცოცხალი მაღაზია / დღეს" : "Live store / today"}</div><h1>{titles[tab]}</h1>{tab === "overview" && <Overview stats={stats} orderQuery={orderQuery} setTab={setTab} language={language} />}{tab === "orders" && <Orders orders={orderQuery.data ?? []} updateFulfillment={updateFulfillment.mutate} language={language} />}{tab === "products" && <Products updateProduct={updateProduct.mutate} productTitle={productTitle} language={language} />}{tab === "settings" && <Settings language={language} />}</main></div><Footer /></div>;
}

function Overview({ stats, orderQuery, setTab, language }: { stats?: { totalSales: number; totalOrders: number; pendingOrders: number; productsInCatalog: number; recentOrders: any[] }; orderQuery: { data?: any[] }; setTab: (tab: "orders") => void; language: "ka" | "en" }) {
  const ka = language === "ka";
  return <><div className="stat-grid"><div className="stat-card"><small>{ka ? "საერთო გაყიდვები" : "Total sales"}</small><strong>{formatPrice(stats?.totalSales ?? 0)}</strong></div><div className="stat-card"><small>{ka ? "საერთო შეკვეთები" : "Total orders"}</small><strong>{stats?.totalOrders ?? 0}</strong></div><div className="stat-card"><small>{ka ? "სამოქმედო" : "Needs action"}</small><strong>{stats?.pendingOrders ?? 0}</strong></div><div className="stat-card"><small>{ka ? "კატალოგი" : "Catalog"}</small><strong>{stats?.productsInCatalog ?? products.length}</strong></div></div><div className="admin-panel"><div className="admin-panel-head"><h2>{ka ? "ბოლო შეკვეთები" : "Recent orders"}</h2><button className="button small secondary" onClick={() => setTab("orders")}>{ka ? "ყველას ნახვა" : "View all"}</button></div><OrderTable orders={orderQuery.data ?? []} compact language={language} /></div><div className="admin-panel" style={{ padding: 20, background: "var(--ink)", color: "var(--paper)" }}><div className="eyebrow" style={{ color: "var(--lime)" }}>{ka ? "მაღაზიის ჩანაწერი" : "Store note"}</div><h2 style={{ font: "600 25px/1 'Space Grotesk'", letterSpacing: "-.06em", margin: "10px 0" }}>4 {ka ? "პოსტერი = უფასო მიტანა." : "posters = free delivery."}</h2><p style={{ color: "#bcbab1", fontSize: 13, margin: 0 }}>{ka ? "ნაკრების ლოგიკა აქტიურია მთელ მაღაზიაში." : "Bundle logic is active across the store."}</p></div></>;
}

function OrderTable({ orders, compact = false, language }: { orders: any[]; compact?: boolean; language: "ka" | "en" }) {
  const ka = language === "ka";
  return <table className="admin-table"><thead><tr><th>{ka ? "კოდი" : "Reference"}</th><th>{ka ? "მომხმარებელი" : "Customer"}</th><th>{ka ? "ჯამი" : "Total"}</th><th>{ka ? "გადახდა" : "Payment"}</th><th>{ka ? "სტატუსი" : "Fulfillment"}</th></tr></thead><tbody>{orders.slice(0, compact ? 5 : 50).map((order) => <tr key={order.id}><td><strong>{order.reference}</strong><br /><span style={{ color: "var(--muted)", fontSize: 11 }}>{new Date(order.createdAt).toLocaleString()}</span></td><td>{order.fullName}<br /><span style={{ color: "var(--muted)", fontSize: 11 }}>{order.city}</span></td><td>{formatPrice(order.total)}</td><td><span className="status">{ka ? "მოლოდინი" : order.paymentStatus}</span></td><td><span className={`status ${order.fulfillmentStatus}`}>{statusKa[order.fulfillmentStatus] ?? order.fulfillmentStatus}</span></td></tr>)}</tbody></table>;
}

function Orders({ orders, updateFulfillment, language }: { orders: any[]; updateFulfillment: (input: { id: number; status: typeof fulfillmentOptions[number] }) => void; language: "ka" | "en" }) {
  const ka = language === "ka";
  return <div className="admin-panel"><div className="admin-panel-head"><h2>{ka ? "შეკვეთების მართვა" : "Order management"}</h2><span className="eyebrow" style={{ color: "var(--muted)" }}>{orders.length} {ka ? "სულ" : "total"}</span></div><table className="admin-table"><thead><tr><th>{ka ? "შეკვეთა" : "Order"}</th><th>{ka ? "მომხმარებელი" : "Customer"}</th><th>{ka ? "ნივთები" : "Items"}</th><th>{ka ? "ჯამი" : "Total"}</th><th>{ka ? "გადახდა" : "Payment"}</th><th>{ka ? "მიწოდება" : "Fulfillment"}</th></tr></thead><tbody>{orders.map((order) => <tr key={order.id}><td><strong>{order.reference}</strong><br /><span style={{ color: "var(--muted)", fontSize: 11 }}>{order.phone}</span></td><td>{order.fullName}<br /><span style={{ color: "var(--muted)", fontSize: 11 }}>{order.address}, {order.city}</span></td><td>{order.items.reduce((sum: number, item: { quantity: number }) => sum + item.quantity, 0)} {ka ? "პოსტერი" : "poster(s)"}</td><td>{formatPrice(order.total)}</td><td><span className="status">{ka ? "მოლოდინი" : order.paymentStatus}</span></td><td><select value={order.fulfillmentStatus} onChange={(event) => updateFulfillment({ id: order.id, status: event.target.value as typeof fulfillmentOptions[number] })} style={{ border: "1px solid var(--line)", padding: "7px 8px", background: "var(--paper)", fontSize: 11 }}>{fulfillmentOptions.map((status) => <option key={status} value={status}>{language === "ka" ? statusKa[status] : status}</option>)}</select></td></tr>)}</tbody></table></div>;
}

function Products({ updateProduct, productTitle, language }: { updateProduct: (input: { id: number; title: string; price: number; stock: number }) => void; productTitle: (product: { title: string; titleKa: string }) => string; language: "ka" | "en" }) {
  const [editing, setEditing] = useState<number | null>(null);
  const [draftTitle, setDraftTitle] = useState("");
  const ka = language === "ka";
  return <div className="admin-panel"><div className="admin-panel-head"><h2>{ka ? "კატალოგის მართვა" : "Catalog CRUD"}</h2><button className="button small coral" onClick={() => alert(ka ? "ახალი პროდუქტის ფორმა მზად არის." : "New product form is ready.")}>+ {ka ? "პროდუქტის დამატება" : "Add product"}</button></div><table className="admin-table"><thead><tr><th>{ka ? "პოსტერი" : "Poster"}</th><th>{ka ? "კატეგორია" : "Category"}</th><th>{ka ? "ფასი" : "Price"}</th><th>{ka ? "მარაგი" : "Stock"}</th><th>{ka ? "მოქმედება" : "Action"}</th></tr></thead><tbody>{products.map((product) => <tr key={product.id}><td style={{ display: "flex", alignItems: "center", gap: 10 }}><img src={product.image} alt="" style={{ width: 34, height: 42, objectFit: "cover", border: "1px solid var(--ink)" }} /><span>{editing === product.id ? <input value={draftTitle} onChange={(event) => setDraftTitle(event.target.value)} style={{ border: "1px solid var(--ink)", padding: 6, width: 180 }} /> : productTitle(product)}</span></td><td style={{ color: "var(--muted)" }}>{product.categoryLabel}</td><td>{formatPrice(product.price)}</td><td>100</td><td>{editing === product.id ? <button className="button small" onClick={() => { updateProduct({ id: product.id, title: draftTitle, price: product.price, stock: 100 }); setEditing(null); }}>{ka ? "შენახვა" : "Save"} <Check size={13} /></button> : <button className="button small secondary" onClick={() => { setEditing(product.id); setDraftTitle(productTitle(product)); }}><Pencil size={13} /> {ka ? "რედაქტირება" : "Edit"}</button>}</td></tr>)}</tbody></table></div>;
}

function Settings({ language }: { language: "ka" | "en" }) {
  const ka = language === "ka";
  return <div className="admin-panel" style={{ padding: 24, maxWidth: 720 }}><div className="eyebrow">{ka ? "მაღაზიის კონფიგურაცია" : "Store configuration"}</div><h2 style={{ font: "600 27px/1 'Space Grotesk'", letterSpacing: "-.06em", margin: "10px 0 26px" }}>{ka ? "საბანკო გადარიცხვის დეტალები" : "Bank transfer details"}</h2><div className="form-grid"><div className="field"><label>{ka ? "ბანკის სახელი" : "Bank name"}</label><input defaultValue="TBC Bank" /></div><div className="field"><label>{ka ? "მიტანის საფასური" : "Shipping fee"}</label><input defaultValue="5.00 ₾" /></div><div className="field full"><label>IBAN</label><input defaultValue="GE00TB0000000000000000" /></div><div className="field full"><label>{ka ? "მიმღების სახელი" : "Receiver name"}</label><input defaultValue="scratchme.ge LLC" /></div></div><button className="button coral" style={{ marginTop: 22 }} onClick={() => alert(ka ? "პარამეტრები მზად არის შესანახად." : "Settings are ready to save.")}>{ka ? "შენახვა" : "Save settings"}</button><p style={{ color: "var(--muted)", fontSize: 12, lineHeight: 1.5, marginTop: 18 }}>{ka ? "ბარათით გადახდის ადაპტერები მზად არის ქართული ბანკების API-ებისთვის." : "Card payment adapters are structured for Georgian bank APIs."}</p></div>;
}
