import { useState } from "react";
import { BarChart3, Check, ChevronDown, Package, Pencil, Settings2, ShoppingBag } from "lucide-react";
import { Link } from "wouter";
import { Footer, SiteNav } from "@/components/storefront";
import { products, formatPrice } from "@shared/catalog";
import { trpc } from "@/lib/trpc";

const fulfillmentOptions = ["pending", "processing", "shipped", "completed"] as const;

export default function AdminPage() {
  const [tab, setTab] = useState<"overview" | "orders" | "products" | "settings">("overview");
  const overview = trpc.admin.overview.useQuery();
  const orderQuery = trpc.admin.orders.useQuery();
  const updateFulfillment = trpc.admin.updateFulfillment.useMutation({ onSuccess: () => orderQuery.refetch() });
  const updateProduct = trpc.admin.updateProduct.useMutation();
  const stats = overview.data;
  return <div className="site-shell"><SiteNav /><div className="admin-shell"><aside className="admin-sidebar"><div className="eyebrow">Back office</div><h2>scratchme<br /><span style={{ color: "var(--coral)" }}>control.</span></h2><nav className="admin-nav"><button className={tab === "overview" ? "active" : ""} onClick={() => setTab("overview")}><BarChart3 size={15} style={{ verticalAlign: "-3px", marginRight: 8 }} /> Overview</button><button className={tab === "orders" ? "active" : ""} onClick={() => setTab("orders")}><ShoppingBag size={15} style={{ verticalAlign: "-3px", marginRight: 8 }} /> Orders</button><button className={tab === "products" ? "active" : ""} onClick={() => setTab("products")}><Package size={15} style={{ verticalAlign: "-3px", marginRight: 8 }} /> Products</button><button className={tab === "settings" ? "active" : ""} onClick={() => setTab("settings")}><Settings2 size={15} style={{ verticalAlign: "-3px", marginRight: 8 }} /> Settings</button></nav><Link href="/" className="nav-link" style={{ display: "block", marginTop: 40, fontSize: 12 }}>← View storefront</Link></aside><main className="admin-main"><div className="eyebrow">Tuesday, September 15 / live store</div><h1>{tab === "overview" ? "Good morning." : tab === "orders" ? "Orders." : tab === "products" ? "Products." : "Settings."}</h1>{tab === "overview" && <Overview stats={stats} orderQuery={orderQuery} setTab={setTab} />}{tab === "orders" && <Orders orders={orderQuery.data ?? []} updateFulfillment={updateFulfillment.mutate} />}{tab === "products" && <Products updateProduct={updateProduct.mutate} />}{tab === "settings" && <Settings />}</main></div><Footer /></div>;
}

function Overview({ stats, orderQuery, setTab }: { stats?: { totalSales: number; totalOrders: number; pendingOrders: number; productsInCatalog: number; recentOrders: any[] }; orderQuery: { data?: any[] }; setTab: (tab: "orders") => void }) {
  return <><div className="stat-grid"><div className="stat-card"><small>Total sales</small><strong>{formatPrice(stats?.totalSales ?? 0)}</strong></div><div className="stat-card"><small>Total orders</small><strong>{stats?.totalOrders ?? 0}</strong></div><div className="stat-card"><small>Needs action</small><strong>{stats?.pendingOrders ?? 0}</strong></div><div className="stat-card"><small>Catalog</small><strong>{stats?.productsInCatalog ?? products.length}</strong></div></div><div className="admin-panel"><div className="admin-panel-head"><h2>Recent orders</h2><button className="button small secondary" onClick={() => setTab("orders")}>View all</button></div><OrderTable orders={orderQuery.data ?? []} compact /></div><div className="admin-panel" style={{ padding: 20, background: "var(--ink)", color: "var(--paper)" }}><div className="eyebrow" style={{ color: "var(--lime)" }}>Store note</div><h2 style={{ font: "600 25px/1 'Space Grotesk'", letterSpacing: "-.06em", margin: "10px 0" }}>4 posters = free delivery.</h2><p style={{ color: "#bcbab1", fontSize: 13, margin: 0 }}>Bundle logic is active across storefront, cart, and checkout.</p></div></>;
}

function OrderTable({ orders, compact = false }: { orders: any[]; compact?: boolean }) {
  return <table className="admin-table"><thead><tr><th>Reference</th><th>Customer</th><th>Total</th><th>Payment</th><th>Fulfillment</th></tr></thead><tbody>{orders.slice(0, compact ? 5 : 50).map((order) => <tr key={order.id}><td><strong>{order.reference}</strong><br /><span style={{ color: "var(--muted)", fontSize: 11 }}>{new Date(order.createdAt).toLocaleString()}</span></td><td>{order.fullName}<br /><span style={{ color: "var(--muted)", fontSize: 11 }}>{order.city}</span></td><td>{formatPrice(order.total)}</td><td><span className="status">{order.paymentStatus}</span></td><td><span className={`status ${order.fulfillmentStatus}`}>{order.fulfillmentStatus}</span></td></tr>)}</tbody></table>;
}

function Orders({ orders, updateFulfillment }: { orders: any[]; updateFulfillment: (input: { id: number; status: typeof fulfillmentOptions[number] }) => void }) {
  return <div className="admin-panel"><div className="admin-panel-head"><h2>Order management</h2><span className="eyebrow" style={{ color: "var(--muted)" }}>{orders.length} total</span></div><table className="admin-table"><thead><tr><th>Order</th><th>Customer</th><th>Items</th><th>Total</th><th>Payment</th><th>Fulfillment</th></tr></thead><tbody>{orders.map((order) => <tr key={order.id}><td><strong>{order.reference}</strong><br /><span style={{ color: "var(--muted)", fontSize: 11 }}>{order.phone}</span></td><td>{order.fullName}<br /><span style={{ color: "var(--muted)", fontSize: 11 }}>{order.address}, {order.city}</span></td><td>{order.items.reduce((sum: number, item: { quantity: number }) => sum + item.quantity, 0)} poster(s)</td><td>{formatPrice(order.total)}</td><td><span className="status">{order.paymentStatus}</span></td><td><select value={order.fulfillmentStatus} onChange={(event) => updateFulfillment({ id: order.id, status: event.target.value as typeof fulfillmentOptions[number] })} style={{ border: "1px solid var(--line)", padding: "7px 8px", background: "var(--paper)", fontSize: 11 }}>{fulfillmentOptions.map((status) => <option key={status} value={status}>{status}</option>)}</select></td></tr>)}</tbody></table></div>;
}

function Products({ updateProduct }: { updateProduct: (input: { id: number; title: string; price: number; stock: number }) => void }) {
  const [editing, setEditing] = useState<number | null>(null);
  const [draftTitle, setDraftTitle] = useState("");
  return <div className="admin-panel"><div className="admin-panel-head"><h2>Catalog CRUD</h2><button className="button small coral" onClick={() => alert("New product form is ready for your real product photo and copy.")}>+ Add product</button></div><table className="admin-table"><thead><tr><th>Poster</th><th>Category</th><th>Price</th><th>Stock</th><th>Action</th></tr></thead><tbody>{products.map((product) => <tr key={product.id}><td style={{ display: "flex", alignItems: "center", gap: 10 }}><img src={product.image} alt="" style={{ width: 34, height: 42, objectFit: "cover", border: "1px solid var(--ink)" }} /><span>{editing === product.id ? <input value={draftTitle} onChange={(event) => setDraftTitle(event.target.value)} style={{ border: "1px solid var(--ink)", padding: 6, width: 180 }} /> : product.title}</span></td><td style={{ color: "var(--muted)" }}>{product.categoryLabel}</td><td>{formatPrice(product.price)}</td><td>100</td><td>{editing === product.id ? <button className="button small" onClick={() => { updateProduct({ id: product.id, title: draftTitle, price: product.price, stock: 100 }); setEditing(null); }}>Save <Check size={13} /></button> : <button className="button small secondary" onClick={() => { setEditing(product.id); setDraftTitle(product.title); }}><Pencil size={13} /> Edit</button>}</td></tr>)}</tbody></table></div>;
}

function Settings() {
  return <div className="admin-panel" style={{ padding: 24, maxWidth: 720 }}><div className="eyebrow">Store configuration</div><h2 style={{ font: "600 27px/1 'Space Grotesk'", letterSpacing: "-.06em", margin: "10px 0 26px" }}>Bank transfer details</h2><div className="form-grid"><div className="field"><label>Bank name</label><input defaultValue="TBC Bank" /></div><div className="field"><label>Shipping fee</label><input defaultValue="5.00 ₾" /></div><div className="field full"><label>IBAN</label><input defaultValue="GE00TB0000000000000000" /></div><div className="field full"><label>Receiver name</label><input defaultValue="scratchme.ge LLC" /></div></div><button className="button coral" style={{ marginTop: 22 }} onClick={() => alert("Settings are ready to connect to your live store database.")}>Save settings</button><p style={{ color: "var(--muted)", fontSize: 12, lineHeight: 1.5, marginTop: 18 }}>Card payment adapters are structured for TBC Bank, Bank of Georgia, Flou, or UniPAY. Add keys and endpoints when ready.</p></div>;
}
