import { ArrowLeft, ArrowRight, Minus, Plus, Trash2 } from "lucide-react";
import { Link } from "wouter";
import { Footer, SiteNav } from "@/components/storefront";
import { useI18n } from "@/lib/i18n";
import { useStore } from "@/lib/store";
import { formatPrice } from "@shared/catalog";

export default function CartPage() {
  const { t, productTitle } = useI18n();
  const { cartItems, cartCount, retailTotal, posterTotal, shipping, total, savings, bundleName, updateQuantity, removeFromCart, showToast } = useStore();
  const categoryName = (category: string) => category === "travel" ? t("nav.travel") : category === "watch" ? t("nav.watch") : t("nav.read");
  if (cartItems.length === 0) return <div className="site-shell"><SiteNav /><main className="container"><div className="page-top"><div className="eyebrow">{t("cart.eyebrow")}</div><h1>{t("cart.emptyTitle")}</h1></div><div className="empty-state"><h2>{t("cart.emptyBody")}</h2><p>{t("cart.emptyBody")}</p><Link href="/shop" className="button" style={{ marginTop: 16 }}>{t("cart.find")} <ArrowRight size={16} /></Link></div></main><Footer /></div>;
  return <div className="site-shell"><SiteNav /><main className="container"><div className="page-top" style={{ paddingBottom: 14 }}><div className="eyebrow">{t("cart.eyebrow")} / {cartCount}</div><h1>{t("cart.good")}</h1><p>{bundleName === "single poster" ? t("bundle.remaining", { count: 1 }) : t("bundle.active", { name: `${cartCount} ${t("bundle.posters")}`, amount: savings.toFixed(2) + " ₾" })}</p></div><div className="cart-layout"><section><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 15 }}><span className="eyebrow">{t("cart.items")}</span><Link href="/shop" className="nav-link" style={{ fontSize: 12 }}><ArrowLeft size={13} style={{ verticalAlign: "-2px" }} /> {t("cart.keep")}</Link></div><div className="cart-list">{cartItems.map(({ product, quantity }) => <div key={product.id} className="cart-item"><img src={product.image} alt={productTitle(product)} /><div><h3>{productTitle(product)}</h3><p>{categoryName(product.category)}</p><div className="qty-control"><button onClick={() => updateQuantity(product.id, quantity - 1)} aria-label="შემცირება"><Minus size={13} /></button><span>{quantity}</span><button onClick={() => updateQuantity(product.id, quantity + 1)} aria-label="გაზრდა"><Plus size={13} /></button></div><br /><button className="remove-btn" onClick={() => { removeFromCart(product.id); showToast(t("toast.removed")); }}><Trash2 size={11} style={{ verticalAlign: "-2px" }} /> {t("cart.remove")}</button></div><div className="cart-item-price">{formatPrice(product.price * quantity)}</div></div>)}</div></section><aside className="summary-card"><div className="eyebrow">{t("cart.summary")}</div><h2>{t("cart.ready")}</h2><BundleProgress count={cartCount} /><div className="summary-line"><span>{t("cart.value")}</span><span>{formatPrice(retailTotal)}</span></div><div className="summary-line"><span>{t("cart.bundle")}</span><span>{formatPrice(posterTotal)}</span></div>{savings > 0 && <div className="bundle-savings"><strong>{t("cart.saved", { amount: formatPrice(savings) })}</strong><br />ფასდაკლება უკვე ავტომატურად ჩაირთო.</div>}<div className="summary-line"><span>{t("cart.delivery")}</span><span>{shipping === 0 ? t("cart.free") : formatPrice(shipping)}</span></div><div className="summary-line total"><span>ჯამი</span><span>{formatPrice(total)}</span></div><Link href="/checkout" className="button coral" style={{ width: "100%", marginTop: 18 }}>{t("cart.checkout")} <ArrowRight size={16} /></Link><p style={{ color: "var(--muted)", fontSize: 11, lineHeight: 1.4, margin: "15px 0 0" }}>{t("cart.paymentNote")}</p></aside></div></main><Footer /></div>;
}

function BundleProgress({ count }: { count: number }) {
  const capped = Math.min(count, 4);
  const message = count >= 4 ? "უფასო მიტანა გახსნილია!" : count === 3 ? "დაამატე 1 პოსტერი უფასო მიტანისთვის" : count === 2 ? "დაამატე 1 პოსტერი — ნაკრები 39.90 ₾" : "დაამატე 1 პოსტერი — ნაკრები 29.90 ₾";
  return <div className="bundle-progress"><div className="bundle-progress-copy"><strong>{message}</strong><span>{capped}/4</span></div><div className="progress-track"><div className="progress-fill" style={{ width: `${(capped / 4) * 100}%` }} />{[2, 3, 4].map((milestone) => <span key={milestone} className={`progress-marker ${count >= milestone ? "reached" : ""}`} style={{ left: `${(milestone / 4) * 100}%` }}>{milestone}</span>)}</div><div className="progress-labels"><span>29.90 ₾</span><span>39.90 ₾</span><span>უფასო მიტანა</span></div></div>;
}
