import { ArrowLeft, ArrowRight, Minus, Plus, Trash2 } from "lucide-react";
import { Link } from "wouter";
import { Footer, SiteNav } from "@/components/storefront";
import { useStore } from "@/lib/store";
import { formatPrice } from "@shared/catalog";

export default function CartPage() {
  const { cartItems, cartCount, retailTotal, posterTotal, shipping, total, savings, bundleName, updateQuantity, removeFromCart } = useStore();
  if (cartItems.length === 0) return <div className="site-shell"><SiteNav /><main className="container"><div className="page-top"><div className="eyebrow">Your scratch stack</div><h1>It is a little<br /><span style={{ color: "var(--coral)" }}>too empty.</span></h1></div><div className="empty-state"><h2>Start with one good idea.</h2><p>Pick a poster and your wall will take it from there.</p><Link href="/shop" className="button" style={{ marginTop: 16 }}>Find a poster <ArrowRight size={16} /></Link></div></main><Footer /></div>;
  return <div className="site-shell"><SiteNav /><main className="container"><div className="page-top" style={{ paddingBottom: 14 }}><div className="eyebrow">Your scratch stack / {cartCount} {cartCount === 1 ? "poster" : "posters"}</div><h1>Good choices.</h1><p>{bundleName === "single poster" ? "Add another poster to unlock bundle pricing." : `Your ${bundleName} is active.`}</p></div><div className="cart-layout"><section><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 15 }}><span className="eyebrow">Items</span><Link href="/shop" className="nav-link" style={{ fontSize: 12 }}><ArrowLeft size={13} style={{ verticalAlign: "-2px" }} /> Keep shopping</Link></div><div className="cart-list">{cartItems.map(({ product, quantity }) => <div key={product.id} className="cart-item"><img src={product.image} alt={product.title} /><div><h3>{product.title}</h3><p>{product.categoryLabel}</p><div className="qty-control"><button onClick={() => updateQuantity(product.id, quantity - 1)} aria-label="Decrease quantity"><Minus size={13} /></button><span>{quantity}</span><button onClick={() => updateQuantity(product.id, quantity + 1)} aria-label="Increase quantity"><Plus size={13} /></button></div><br /><button className="remove-btn" onClick={() => removeFromCart(product.id)}><Trash2 size={11} style={{ verticalAlign: "-2px" }} /> Remove</button></div><div className="cart-item-price">{formatPrice(product.price * quantity)}</div></div>)}</div></section><aside className="summary-card"><div className="eyebrow">Order summary</div><h2>Ready when<br />you are.</h2><div className="summary-line"><span>Poster value</span><span>{formatPrice(retailTotal)}</span></div><div className="summary-line"><span>Bundle price</span><span>{formatPrice(posterTotal)}</span></div>{savings > 0 && <div className="bundle-savings"><strong>You saved {formatPrice(savings)}.</strong><br />Bundle pricing is already applied to your stack.</div>}<div className="summary-line"><span>Delivery</span><span>{shipping === 0 ? "FREE" : formatPrice(shipping)}</span></div><div className="summary-line total"><span>Total</span><span>{formatPrice(total)}</span></div><Link href="/checkout" className="button coral" style={{ width: "100%", marginTop: 18 }}>Checkout <ArrowRight size={16} /></Link><p style={{ color: "var(--muted)", fontSize: 11, lineHeight: 1.4, margin: "15px 0 0" }}>Bank transfer is active. Card payments are ready to connect when your gateway keys are added.</p></aside></div></main><Footer /></div>;
}
